version: '3.8'
services:
  server:
    container_name: server
    image: fridgy/server
    env_file:
      - .env
  frontend:
    container_name: frontend
    image: fridgy/frontend
    ports:
      - 8088:80
    env_file:
      - .env
    volumes:
      - .\nginx.conf:/etc/nginx/nginx.conf